#include<iostream>
#include<csignal>
#include<thread>
#include<functional>


void sigterm_handler(int signal)
{ 
    static std::uint32_t count = 0;
    std::cout << "\n[sigterm " << signal << " handled in " << std::this_thread::get_id() << ", count = " << count << "]  " << std::flush;
    ++count;
}

void sigsegv_handler(int signal)
{ 
    static std::uint32_t count = 0;
    std::cout << "\n[sigsegv " << signal << " handled in " << std::this_thread::get_id() << ", count = " << count << "]  " << std::flush;
    ++count;
}

void sigint_handler(int signal)
{ 
    static std::uint32_t count = 0;
    std::cout << "\n[sigint " << signal << " handled in " << std::this_thread::get_id() << ", count = " << count << "]  " << std::flush;
    ++count;
}

void sigill_handler(int signal)
{ 
    static std::uint32_t count = 0;
    std::cout << "\n[sigill " << signal << " handled in " << std::this_thread::get_id() << ", count = " << count << "]  " << std::flush;
    ++count;
}

// *********************** //
// *** Signal-and-slot *** //
// *********************** //
// Observation :
// 1. signal generated by std::raise invokes handler with same thread as std::raise
// 2. signal generated by ctrl-C     invokes handler with main thread
// 3. even main thread is busy with its task, it is interrupted to run handler

void test_signal()
{
    std::cout << "\nEntering ctrl-C, we will get more count for SIGINT. Main thread is " << std::this_thread::get_id() << std::flush;

    std::signal(SIGTERM, sigterm_handler); 
    std::signal(SIGSEGV, sigsegv_handler); 
    std::signal(SIGINT,   sigint_handler); // SIGINT = ctrl-C
    std::signal(SIGILL,   sigill_handler);

    std::thread t([]()
    {
        for(std::uint32_t n=0; n!=12; ++n)
        {
            if      (n%4==0) std::raise(SIGTERM);
            else if (n%4==1) std::raise(SIGSEGV);
            else if (n%4==2) std::raise(SIGINT);
            else if (n%4==3) std::raise(SIGILL);
        //  kill(0, SIGINT); // equivalent to std::raise

            std::cout << "\nSpawned thread " << std::this_thread::get_id() << " interruptable-task : " << std::flush;
            for(std::uint32_t m=0; m!=10; ++m)
            {
                std::cout << m << std::flush;
                std::this_thread::sleep_for(std::chrono::milliseconds(100));
            }
        }
    });
    
    // Main thread
    for(std::uint32_t n=0; n!=10; ++n)
    {
        std::cout << " [$] " << std::flush;
        std::this_thread::sleep_for(std::chrono::milliseconds(1000));
    }
    t.join();
}
